# cloud-config.yml

instances:
  - name: instance-1
    machine_type: n1-standard-1
    source_image: ubuntu-20-04
    zone: us-central1-a
    project: ansible4devops
    ssh_public_key: "ssh-rsa /home/mailbox4prakhar/.ssh/id_rsa.pub  mailbox4prakhar@gmail.com"

  - name: instance-2
    machine_type: n1-standard-2
    source_image: debian-10
    zone: us-west1-b
    project: ansible4devops
    ssh_public_key: "ssh-rsa /home/mailbox4prakhar/.ssh/id_rsa.pub mailbox4prakhar@gmail.com"


